export type ThemeMode = 'pink' | 'matcha' | 'lavender' | 'butter';

export const themeClasses = {
  pink: {
    name: 'Strawberry Pink',
    bgLight: 'bg-pink-50',
    bgLightHalf: 'bg-pink-50/50',
    bgPrimary: 'bg-pink-500',
    textPrimary: 'text-pink-500',
    textMedium: 'text-pink-400',
    textDark: 'text-pink-600',
    textLight: 'text-pink-300',
    borderLight: 'border-pink-100',
    borderMedium: 'border-pink-200',
    shadowLight: 'shadow-pink-200',
    hoverBgPrimary: 'hover:bg-pink-600',
    hoverBgLight: 'hover:bg-pink-50',
    hoverTextPrimary: 'hover:text-pink-500',
    hoverTextDark: 'hover:text-pink-600',
    hoverBorderLight: 'hover:border-pink-200',
    hoverBorderMedium: 'hover:border-pink-300',
    hoverShadowMedium: 'hover:shadow-pink-300',
    selectionBg: 'selection:bg-pink-200',
    selectionText: 'selection:text-pink-900',
    fillCurrent: 'text-pink-400 fill-current',
    blob1: 'bg-pink-200',
    blob2: 'bg-rose-200',
    blob3: 'bg-rose-300',
    blob4: 'bg-pink-400',
  },
  matcha: {
    name: 'Matcha Green',
    bgLight: 'bg-emerald-50',
    bgLightHalf: 'bg-emerald-50/50',
    bgPrimary: 'bg-emerald-500',
    textPrimary: 'text-emerald-500',
    textMedium: 'text-emerald-400',
    textDark: 'text-emerald-600',
    textLight: 'text-emerald-300',
    borderLight: 'border-emerald-100',
    borderMedium: 'border-emerald-200',
    shadowLight: 'shadow-emerald-200',
    hoverBgPrimary: 'hover:bg-emerald-600',
    hoverBgLight: 'hover:bg-emerald-50',
    hoverTextPrimary: 'hover:text-emerald-500',
    hoverTextDark: 'hover:text-emerald-600',
    hoverBorderLight: 'hover:border-emerald-200',
    hoverBorderMedium: 'hover:border-emerald-300',
    hoverShadowMedium: 'hover:shadow-emerald-300',
    selectionBg: 'selection:bg-emerald-200',
    selectionText: 'selection:text-emerald-900',
    fillCurrent: 'text-emerald-400 fill-current',
    blob1: 'bg-emerald-200',
    blob2: 'bg-teal-200',
    blob3: 'bg-teal-300',
    blob4: 'bg-emerald-400',
  },
  lavender: {
    name: 'Lavender Dream',
    bgLight: 'bg-violet-50',
    bgLightHalf: 'bg-violet-50/50',
    bgPrimary: 'bg-violet-500',
    textPrimary: 'text-violet-500',
    textMedium: 'text-violet-400',
    textDark: 'text-violet-600',
    textLight: 'text-violet-300',
    borderLight: 'border-violet-100',
    borderMedium: 'border-violet-200',
    shadowLight: 'shadow-violet-200',
    hoverBgPrimary: 'hover:bg-violet-600',
    hoverBgLight: 'hover:bg-violet-50',
    hoverTextPrimary: 'hover:text-violet-500',
    hoverTextDark: 'hover:text-violet-600',
    hoverBorderLight: 'hover:border-violet-200',
    hoverBorderMedium: 'hover:border-violet-300',
    hoverShadowMedium: 'hover:shadow-violet-300',
    selectionBg: 'selection:bg-violet-200',
    selectionText: 'selection:text-violet-900',
    fillCurrent: 'text-violet-400 fill-current',
    blob1: 'bg-violet-200',
    blob2: 'bg-purple-200',
    blob3: 'bg-purple-300',
    blob4: 'bg-violet-400',
  },
  butter: {
    name: 'Vanilla Butter',
    bgLight: 'bg-amber-50',
    bgLightHalf: 'bg-amber-50/50',
    bgPrimary: 'bg-amber-500',
    textPrimary: 'text-amber-500',
    textMedium: 'text-amber-400',
    textDark: 'text-amber-600',
    textLight: 'text-amber-300',
    borderLight: 'border-amber-100',
    borderMedium: 'border-amber-200',
    shadowLight: 'shadow-amber-200',
    hoverBgPrimary: 'hover:bg-amber-600',
    hoverBgLight: 'hover:bg-amber-50',
    hoverTextPrimary: 'hover:text-amber-500',
    hoverTextDark: 'hover:text-amber-600',
    hoverBorderLight: 'hover:border-amber-200',
    hoverBorderMedium: 'hover:border-amber-300',
    hoverShadowMedium: 'hover:shadow-amber-300',
    selectionBg: 'selection:bg-amber-200',
    selectionText: 'selection:text-amber-900',
    fillCurrent: 'text-amber-400 fill-current',
    blob1: 'bg-amber-200',
    blob2: 'bg-orange-200',
    blob3: 'bg-orange-300',
    blob4: 'bg-amber-400',
  }
};